### ISSUE TITLE
Не совпадают значения publicId в криптограмме и аутентификационных данных

### ISSUE THREAD

**Issue by ByteToByte** [kettari/cloud_payments#15]
По сабжу
Не совпадают значения publicId в криптограмме и аутентификационных данных

В тестовом режиме. 
Но уведомление о оплате приходит оплачено успешно.

**Comment by kettari** [comment]
Здравствуйте. С марта 2019 года поддержку плагина осуществляет CloudPayments самостоятельно. Пожалуйста, обратитесь в их службу поддержки.
